# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preprocessed_images.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from for_segmentation import image_pp_segmentation
import cv2

class Ui_SecondWindow(object):

    def __init__(self,path):
            self.path = path
            self.processed_image, self.clustered_image, self.hsv, self.blur, self.before_pp = image_pp_segmentation(self.path)
            h,w,c = self.before_pp.shape
            bpl = 3*w
            self.before_pp = QtGui.QImage(self.before_pp.data,w,h,bpl,QtGui.QImage.Format_RGB888).rgbSwapped()
            self.blur = QtGui.QImage(self.blur.data, w, h, bpl, QtGui.QImage.Format_RGB888).rgbSwapped()
            cv2.imwrite('hsv_temp.jpg',self.hsv)
           # self.hsv = QtGui.QImage(self.hsv.data, w1, h1, bpl, QtGui.QImage.Format_RGB888)
            self.clustered_image = QtGui.QImage(self.clustered_image.data, w, h, bpl, QtGui.QImage.Format_RGB888).rgbSwapped()
            self.processed_image = QtGui.QImage(self.processed_image.data, w, h, bpl, QtGui.QImage.Format_RGB888).rgbSwapped()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Main Window")
        MainWindow.resize(750, 553)
        MainWindow.setStyleSheet("background-color:rgb(0, 235, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, -10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 711, 481))
        self.groupBox.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:14px;")
        self.groupBox.setObjectName("Group Box")
        self.original = QtWidgets.QLabel(self.groupBox)
        self.original.setGeometry(QtCore.QRect(40, 80, 141, 151))
        self.original.setStyleSheet("border-radius:14px;")
        self.original.setText("")
        self.original.setPixmap(QtGui.QPixmap(self.before_pp))
        self.original.setScaledContents(True)
        self.original.setObjectName("original")
        self.removed_noise = QtWidgets.QLabel(self.groupBox)
        self.removed_noise.setGeometry(QtCore.QRect(290, 80, 141, 151))
        self.removed_noise.setStyleSheet("border-radius:14px;")
        self.removed_noise.setText("")
        self.removed_noise.setPixmap(QtGui.QPixmap(self.blur))
        self.removed_noise.setScaledContents(True)
        self.removed_noise.setObjectName("removed_noise")
        self.hsv = QtWidgets.QLabel(self.groupBox)
        self.hsv.setGeometry(QtCore.QRect(530, 80, 141, 151))
        self.hsv.setStyleSheet("border-radius:14px;")
        self.hsv.setText("")
        self.hsv.setPixmap(QtGui.QPixmap("hsv_temp.jpg"))
        self.hsv.setScaledContents(True)
        self.hsv.setObjectName("hsv")
        self.cluster = QtWidgets.QLabel(self.groupBox)
        self.cluster.setGeometry(QtCore.QRect(370, 320, 141, 151))
        self.cluster.setStyleSheet("border-radius:14px;")
        self.cluster.setText("")
        self.cluster.setPixmap(QtGui.QPixmap(self.clustered_image))
        self.cluster.setScaledContents(True)
        self.cluster.setObjectName("cluster")
        self.final_2 = QtWidgets.QLabel(self.groupBox)
        self.final_2.setGeometry(QtCore.QRect(100, 310, 151, 161))
        self.final_2.setStyleSheet("border-radius:14px;")
        self.final_2.setText("")
        self.final_2.setPixmap(QtGui.QPixmap(self.processed_image))
        self.final_2.setScaledContents(True)
        self.final_2.setObjectName("final_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgb(170, 255, 127);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(530, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:rgb(170, 255, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(290, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgb(170, 255, 127);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(360, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:rgb(170, 255, 127);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(100, 270, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:rgb(170, 255, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.arrow = QtWidgets.QLabel(self.groupBox)
        self.arrow.setGeometry(QtCore.QRect(190, 130, 81, 41))
        self.arrow.setText("")
        self.arrow.setPixmap(QtGui.QPixmap("assets//Green-Arrow-Transparent-Background.png"))
        self.arrow.setScaledContents(True)
        self.arrow.setObjectName("arrow")
        self.arrow_2 = QtWidgets.QLabel(self.groupBox)
        self.arrow_2.setGeometry(QtCore.QRect(440, 140, 81, 41))
        self.arrow_2.setText("")
        self.arrow_2.setPixmap(QtGui.QPixmap("assets//Green-Arrow-Transparent-Background.png"))
        self.arrow_2.setScaledContents(True)
        self.arrow_2.setObjectName("arrow_2")
        self.arrow_3 = QtWidgets.QLabel(self.groupBox)
        self.arrow_3.setGeometry(QtCore.QRect(270, 360, 81, 41))
        self.arrow_3.setText("")
        self.arrow_3.setPixmap(QtGui.QPixmap("assets//Green-Arrow-Transparent-Background2.png"))
        self.arrow_3.setScaledContents(True)
        self.arrow_3.setObjectName("arrow_3")
        self.arrow_4 = QtWidgets.QLabel(self.groupBox)
        self.arrow_4.setGeometry(QtCore.QRect(590, 250, 41, 91))
        self.arrow_4.setText("")
        self.arrow_4.setPixmap(QtGui.QPixmap("assets//Green-Arrow-Transparent-Background3.png"))
        self.arrow_4.setScaledContents(True)
        self.arrow_4.setObjectName("arrow_4")
        self.arrow_5 = QtWidgets.QLabel(self.groupBox)
        self.arrow_5.setGeometry(QtCore.QRect(530, 350, 81, 41))
        self.arrow_5.setText("")
        self.arrow_5.setPixmap(QtGui.QPixmap("assets//Green-Arrow-Transparent-Background2.png"))
        self.arrow_5.setScaledContents(True)
        self.arrow_5.setObjectName("arrow_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preprocessing of Images"))
        self.label.setText(_translate("MainWindow", "Step wise Processed Images "))
        self.groupBox.setTitle(_translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", "Original Image"))
        self.label_8.setText(_translate("MainWindow", "HSV Image"))
        self.label_9.setText(_translate("MainWindow", "Noise Removed"))
        self.label_10.setText(_translate("MainWindow", "Clusters by K means"))
        self.label_11.setText(_translate("MainWindow", "Final Image"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
